// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3bnMTfA6XxqOuda4_r_HVfZU7C7vdl0I',
    appId: '1:744441487240:web:3436a380e13bacd92ee43d',
    messagingSenderId: '744441487240',
    projectId: 'flards',
    authDomain: 'flards.firebaseapp.com',
    storageBucket: 'flards.firebasestorage.app',
    measurementId: 'G-404NJ3CTQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNUys7kcxSyzBE0Um7DIak0NgsS76hRE',
    appId: '1:744441487240:android:4ef271c9cd14b9b62ee43d',
    messagingSenderId: '744441487240',
    projectId: 'flards',
    storageBucket: 'flards.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEBUQiPRVhWzMu0KYUOih9I-SXgogQNIM',
    appId: '1:744441487240:ios:7e82d5a04357aab42ee43d',
    messagingSenderId: '744441487240',
    projectId: 'flards',
    storageBucket: 'flards.firebasestorage.app',
    iosBundleId: 'com.example.flard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEBUQiPRVhWzMu0KYUOih9I-SXgogQNIM',
    appId: '1:744441487240:ios:7e82d5a04357aab42ee43d',
    messagingSenderId: '744441487240',
    projectId: 'flards',
    storageBucket: 'flards.firebasestorage.app',
    iosBundleId: 'com.example.flard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3bnMTfA6XxqOuda4_r_HVfZU7C7vdl0I',
    appId: '1:744441487240:web:bf5501e78ab26aa32ee43d',
    messagingSenderId: '744441487240',
    projectId: 'flards',
    authDomain: 'flards.firebaseapp.com',
    storageBucket: 'flards.firebasestorage.app',
    measurementId: 'G-Z47QTK8LJW',
  );

}